
crypto_map: VPN
crypto_map_interface: GigabitEthernet2
crypto_map_source_interface: Loopback0

ipsec_tunnels:

  - tunnel_name: partner1
    seq: 10
    peer_ip: 172.16.252.1
    transform_encryption: esp-3des
    transform_auth: esp-md5-hmac
    isakmp_encr: aes
    isakmp_auth: pre-share
    isakmp_key: cisco
    acl_lines:
      - permit ip host 1.1.1.1 host 2.2.2.2
      - permit ip 192.168.0.0 0.0.0.255 192.168.1.0 0.0.0.255

  - tunnel_name: partner2
    seq: 20
    peer_ip: 172.16.252.2
    transform_encryption: esp-3des
    transform_auth: esp-md5-hmac
    isakmp_encr: aes
    isakmp_auth: pre-share
    isakmp_key: cisco
    acl_lines:
      - permit ip 192.168.0.0 0.0.0.255 192.168.2.0 0.0.0.255

  - tunnel_name: partner3
    seq: 30
    peer_ip: 172.16.252.3
    transform_encryption: esp-3des
    transform_auth: esp-md5-hmac
    isakmp_encr: aes
    isakmp_auth: pre-share
    isakmp_key: cisco
    acl_lines:
      - permit ip 192.168.0.0 0.0.0.255 192.168.3.0 0.0.0.255

  - tunnel_name: partner4
    seq: 40
    peer_ip: 172.16.252.4
    transform_encryption: esp-3des
    transform_auth: esp-md5-hmac
    isakmp_encr: aes
    isakmp_auth: pre-share
    isakmp_key: cisco
    acl_lines:
      - permit ip 192.168.0.0 0.0.0.255 192.168.4.0 0.0.0.255
